version: "3"
services:
  namenode:
    image: apache/hadoop:3
    container_name: namenode
    platform: linux/amd64
    hostname: namenode
    command: ["hdfs", "namenode"]
    ports:
      - 9870:9870
      - 8020:8020
    env_file:
      - ./config
    environment:
        ENSURE_NAMENODE_DIR: "/tmp/hadoop-root/dfs/name"
    volumes:
      - ./data/:/data/
  datanode:
    image: apache/hadoop:3
    container_name: datanode
    platform: linux/amd64
    command: ["hdfs", "datanode"]
    env_file:
      - ./config      
  resourcemanager:
    image: apache/hadoop:3
    container_name: resourcemanager
    platform: linux/amd64
    hostname: resourcemanager
    command: ["yarn", "resourcemanager"]
    ports:
        - 8088:8088
        - 8032:8032
    env_file:
      - ./config
  nodemanager:
    image: apache/hadoop:3
    container_name: nodemanager
    platform: linux/amd64
    command: ["yarn", "nodemanager"]
    env_file:
      - ./config

  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: docker.io/bitnami/kafka:3.3
    container_name: kafka
    hostname: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  spark-master:
    image: bitnami/spark:3.3
    container_name: spark-master
    command: bin/spark-class org.apache.spark.deploy.master.Master
    ports:
      - 8080:8080
      - 7077:7077
      - 4040:4040

    volumes:
      - ./data:/data/
      - ./:/src/

  spark-worker-1:
    image: bitnami/spark:3.3
    container_name: spark-worker-1
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    environment:
      SPARK_MODE: worker
      SPARK_WORKER_CORES: 4
      SPARK_WORKER_MEMORY: 8g
      SPARK_EXECUTOR_MEMORY: 8G
      SPARK_MASTER_URL: spark://spark-master:7077

    volumes:
      - ./data:/data/
      - ./:/src/


