version: "3"

x-spark-common: 
  &spark-common
  image: bitnami/spark:3.3
  restart: unless-stopped
  volumes:
    - ./spark/:/src/

services:
  spark-master:
    <<: *spark-common
    container_name: spark-master
    command: bin/spark-class org.apache.spark.deploy.master.Master
    hostname: spark-master
    ports:
      - 8080:8080
      - 7077:7077
      - 4040:4040
    

  spark-worker-1:
    <<: *spark-common
    container_name: spark-worker-1
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    environment:
      SPARK_MODE: worker
      SPARK_WORKER_CORES: 4
      SPARK_WORKER_MEMORY: 8g
      SPARK_EXECUTOR_MEMORY: 8G
      SPARK_MASTER_URL: spark://spark-master:7077