version: '3'

services:
  superset:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: superset
    environment:
      - ADMIN_USERNAME=admin
      - ADMIN_EMAIL=admin@superset.com
      - ADMIN_PASSWORD=admin
    ports:
      - '8089:8088'
    networks:
      - music_streaming_event_default
    volumes:
      - ./dashboard_data/:/app/superset_home/
  
networks:
  music_streaming_event_default:
    external: True