version: '3'

services:
  superset:
    image: superset:latest
    container_name: superset
    environment:
      - ADMIN_USERNAME=admin
      - ADMIN_EMAIL=admin@superset.com
      - ADMIN_PASSWORD=admin
    ports:
      - '8089:8088'
    volumes:
      - ./superset/dashboard_data/:/app/superset_home/
    restart: unless-stopped