version: "3"

services:
  cassandra:
    image: cassandra:4.0
    platform: linux/amd64
    container_name: cassandra
    hostname: cassandra
    ports:
      - 7000:7000
      - 9042:9042
      - 7001:7001
      - 9160:9160
      - 7199:7199
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "describe keyspaces" ]
      interval: 5s
      timeout: 5s
      retries: 60
    volumes:
      - ./data:/var/lib/cassandra
    environment:
      - CASSANDRA_BROADCAST_ADDRESS=cassandra
      - MAX_HEAP_SIZE=256M
      - HEAP_NEWSIZE=128M
      
    restart: always
    networks:
      - music_streaming_event_default
  cassandra-load-keyspace:
    container_name: cassandra-load-keyspace
    image: cassandra:4.0
    platform: linux/amd64
    depends_on:
      cassandra:
        condition: service_healthy
    working_dir: /cassandra
    volumes:
      - ./scripts/:/cassandra
    command: /bin/bash -c "echo loading cassandra keyspace && sh ./initialize_schema.sh"
    networks:
      - music_streaming_event_default
networks:
  music_streaming_event_default:
    external: True