version: "3"

services:
  cassandra:
    image: cassandra:4.0
    platform: linux/amd64
    container_name: cassandra
    hostname: cassandra
    ports:
      - 7000:7000
      - 9042:9042
      - 7001:7001
      - 9160:9160
      - 7199:7199
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "describe keyspaces" ]
      interval: 5s
      timeout: 5s
      retries: 60
    working_dir: 
     "/cassandra"
    volumes:
      - ./:/cassandra
    networks:
      - music_streaming_event_default
    environment:
      - CASSANDRA_BROADCAST_ADDRESS=cassandra

networks:
  music_streaming_event_default:
    external: true